
//action type constants

//product related
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const ERROR_FETCHING_PRODUCTS = "ERROR_FETCHING_PRODUCTS"
export const ADD_PRODUCTS = "ADD_PRODUCTS"
export const TOGGLE_SELECT_PRODUCT = "TOGGLE_SELECT_PRODUCT"


//customer details related
export const FETCH_CUSTOMER_DETAILS = "FETCH_CUSTOMER_DETAILS"
export const ERROR_FETCHING_CUSTOMER_DETAILS = "ERROR_FETCHING_CUSTOMER_DETAILS"
export const ADD_CUSTOMER_DETAILS = "ADD_CUSTOMER_DETAILS"

//checkout
export const CHECKOUT = "CHECKOUT"
export const ERROR_WITH_CHECKOUT = "ERROR_WITH_CHECKOUT"
export const ADD_CHECKOUT_CONFIRM = "ADD_CHECKOUT_CONFIRM"
